spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/reservas
spring.datasource.username=postgresbX9#vK2$mZ_qL8wT!xP4
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=local